name: 'Tests with Doctrine Message Repository version 3'

on:
    push:
        branches:
            - master
            - 2.x

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        container: shivammathur/node:latest
        strategy:
            max-parallel: 10
            matrix:
                php: ['8.5']

        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: phpstan
                  coverage: pcov

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download dependencies
              run: |
                  composer config minimum-stability dev
                  composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable
                  composer require --no-interaction eventsauce/message-repository-for-doctrine 

            - name: Run tests
              run: ./vendor/bin/phpunit

            - name: Run PHPStan
              run: phpstan analyse